#!/usr/bin/python 

from optparse import OptionParser
import validator, revalidation_service

parser = OptionParser()
parser.add_option("-v", "--verbose",
                  action="store_false", dest="verbose", default=True,
                  help="don't print status messages to stdout but to the pr")

(options, args) = parser.parse_args()

if len(args) == 1:
    jimaek = validator.PullBot()
    if args[0] == 'all':
      revalidation_service.check_all_open_prs(jimaek)
    else:
      jimaek.validate(int(args[0]), options.verbose)
    print 'LGTM'
else:
    print "Format: $ cli <pr> --verbose=false"